language: ruby
script:
  - bundle exec rspec
jdk:
  - openjdk7
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
allow_failures:
  - rvm: jruby-18mode
  - rvm: jruby-19mode
notifications:
  recipients:
    - brixen@gmail.com
