#!/bin/sh
#
# /etc/init.d/cron
#
# Rcsid = $Id: cron#2 2007/10/11 09:16:35 FAREAST\\dbansa $


CRON=/usr/sbin/cron
PATH=/bin:/usr/contrib/bin

. /etc/init.d/funcs

case $1 in
	start)
		${CRON}
		[ $? = 0 ] && echo "cron started"
		;;
	stop)
		killall cron
		[ $? = 0 ] && echo "cron stopped"
		;;

	*)
		echo "usage: $0 start|stop"
		;;
	esac
exit 0
