#!/bin/sh

#
# /etc/init.d/inetd
#
# Rcsid = $Id: inet#2 2007/10/11 09:16:35 FAREAST\\dbansa $

PATH=/bin:/usr/contrib/bin
INETD=/usr/sbin/inetd

. /etc/init.d/funcs

case $1 in
	start)
		${INETD}
		[ $? = 0 ] && echo "inetd started"
		;;
	stop)
		killall inetd
		[ $? = 0 ] && echo "inetd stopped"
		;;
	*)
		echo "usage: $0 start|stop"
		;;
	esac
exit 0
