#!/bin/sh

# /etc/init.d/rpc
#  - script to start portmap service
#    It ships installed as "manual start" so we have to force the startup
#
. /etc/init.d/funcs
PATH=/bin:/usr/contrib/bin:/usr/contrib
case $1 in
    start)
	echo "Starting portmap service"
	/usr/contrib/win32/bin/net start portmap
	if [ $? != 0 ]; then
	   echo "Note: it may be alright if "net start" command failed here\n"\
	       "because portmap service may already be running.\n" 
	fi
	;;
    stop)
	/usr/contrib/win32/bin/net stop portmap
	;;
    esac
exit 0
