#!/bin/sh

#
# /etc/init.d/sendmail
#
# Rcsid = $Id: sendmail#2 2007/10/11 09:16:35 FAREAST\\dbansa $


SENDMAIL=/usr/sbin/sendmail
PATH=/bin:/usr/contrib/bin

. /etc/init.d/funcs

case $1 in
	start)
		##
		## sendmail daemon disabled by default.
		## If you want to run sendmail as an SMTP server
		## (ie recieve remote mail)
		## then you have to make sure you have no other
		## SMTP servers running on your system
		## before you uncomment the next few lines.
		##
		## And you have to make sure your /etc/mail/sendmail.cf
		## is configured properly
		##
		#   ${SENDMAIL}  -bd -q30m &
		#   [ $? = 0 ] && echo "sendmail started"

		;;
	stop)
		killall sendmail
		[ $? = 0 ] && echo "sendmail stopped"
		;;
	*)
		echo "usage: $0 start|stop"
		;;
	esac
exit 0
