#!/bin/sh

#
# /etc/init.d/syslog
#
# Rcsid = $Id: syslog#2 2007/03/30 06:17:10 FAREAST\\apekshag $


SYSLOGD=/usr/sbin/syslogd
PATH=/bin:/usr/contrib/bin

. /etc/init.d/funcs

case $1 in
	start)
        ##
        ## syslogd daemon is disabled by default.
        ## If you want to run syslogd then you
        ## have to uncomment the next few lines.
        ##
		#   ${SYSLOGD}
		#   [ $? = 0 ] && echo "syslogd started"
		;;
	stop)
		killall syslogd
		[ $? = 0 ] && echo "syslogd stopped"
		;;
	*)
		echo "usage: $0 start|stop"
		;;
	esac
exit 0
